### ISSUE TITLE
Vistual Studio 2022 crashes when trying to open flghtdata.cs

### ISSUE THREAD

**Issue by danilopmaciel** [ArduPilot/MissionPlanner#3399] opened 2024-08-29 17:01 UTC
![image](https://github.com/user-attachments/assets/bca64e52-c91e-4a03-b262-2f48d622961b)

When trying to open flightdata.cs, ​​Visual Studio crashes and restarts. Sometimes it shows this error screen. This is happening on different computers. I cloned the repository and I'm just trying to open it and this happens on 3 different computers using Windows 11.

Can anyone help-me?

**Comment by EosBandi** [comment] 2024-08-29 17:20
duplicate of https://github.com/ArduPilot/MissionPlanner/issues/3306 
See possible remedies there

**Closed by EosBandi** 2024-08-29 17:20 UTC
