### ISSUE TITLE
DataFlash Log view not showing mode?

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2008] opened 2018-11-28 10:20 UTC
![no-mode-shown](https://user-images.githubusercontent.com/1498098/49145164-8506b300-f342-11e8-91ac-645f2e9cc160.png)
I think the dataflash log viewer is no longer showing the mode down at the bottom.  Normally the bar at the bottom also shows different colours depending upon the mode.

This is a 3.6.1 log.

**Comment by meee1** [comment] 2018-11-28 10:48
this one is a bug, and fixed in latest beta.

**Comment by meee1** [comment] 2018-11-28 10:51
duplicate of #2006

**Closed by meee1** 2018-11-28 10:51 UTC
Labels: arducopter, bug

**Comment by rmackay9** [comment] 2018-11-28 10:58
Indeed it's fixed in the latest beta, thanks!
