### ISSUE TITLE
Auto WP -> Survey grid layout error in complex shapes

### ISSUE THREAD

**Issue by suraqis** [ArduPilot/MissionPlanner#1679] opened 2017-11-06 17:27 UTC
#### Issue details
When Auto WP Survey Grid is built it fails on complex polygon shapes (with concavities). Image attached 
![image](https://user-images.githubusercontent.com/7581666/32454463-f816860a-c327-11e7-87b0-33054a6edcf8.png)

May it be a good solution - just ignore concavities when building layout and accept concavities when turning shutter control? Often it's takes less time to fly over all concavities but it takes a lot of space and processing time to keep photo from not interested area.

#### Version
Mission Planner 1.3.50

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Fixed Wing_

#### Hardware type
All

#### Logs
No need

**Comment by meee1** [comment] 2017-11-06 22:25
please provide the grid file use to generate this grid.


in the grid interface press control-s

**Comment by anestetico** [comment] 2018-08-22 21:06
The problem is still there but only affects users doing very large areas, anyway just a simple polygon like attached shows the problem, sometimes you can resolve by tweaking the angle, but not in complex polygons.
Thank you
![missionplanner_2018-08-22_18-04-13](https://user-images.githubusercontent.com/6798659/44490873-f2b18d80-a635-11e8-923e-ad50316f2ed2.png)
[test.zip](https://github.com/ArduPilot/MissionPlanner/files/2312014/test.zip)

**Comment by anestetico** [comment] 2018-09-05 19:16
![missionplanner_2018-09-05_16-11-23](https://user-images.githubusercontent.com/6798659/45115710-04f7f500-b127-11e8-82ae-664ce4a0600e.png)

**Comment by Naterater** [comment] 2018-12-02 14:32
10/10 Fixed! Thank you so much!!!

![image](https://user-images.githubusercontent.com/35429159/49340983-a995b000-f60c-11e8-98f4-ccf7aa0686bd.png)

**Comment by anestetico** [comment] 2018-12-02 22:38
> 10/10 Fixed! Thank you so much!!!
> 
> ![image](https://user-images.githubusercontent.com/35429159/49340983-a995b000-f60c-11e8-98f4-ccf7aa0686bd.png)

Look at your pictures, there are still strange paths, I downloaded latest beta and it seems better but not 100%
![missionplanner_2018-12-02_19-36-29](https://user-images.githubusercontent.com/6798659/49345892-bac0da00-f669-11e8-8b31-d2991a9a532c.png)

**Comment by meee1** [comment] 2018-12-02 23:12
you will never get 100% because of the shape you are flying. there will always be lines that will need to navigate to without being part of the grid. if you where to change the angle, you could possible find a more suitable flight line that had less transit paths.

**Comment by anestetico** [comment] 2018-12-02 23:51
Qgroundcontrol acts different, maybe sometimes is better and sometimes not, btw thank you very much for the fix, it will help a lot.
For the Corridor function would be possible to add corridor option and corridor width when saving *.grid file? If you load a previously saved file you have to remember that is a corridor (not difficult) and its width.

**Comment by Naterater** [comment] 2018-12-03 00:47
The "strange paths" are where it goes to finish sections. I don't consider them strange although I would prefer if it would turn the camera off on those paths. Super-crazy shapes with a million vertices are a very rare corner case, however L-Shaped fields are not.

Now that we are continuing the discussion, I would like to continue this improvement. 

#1 - Keep as many turns in the same direction as possible (ie - Into the wind). For the example above, consider the wind coming from the southwest. Mapping with a crosswind and turning into the wind is ideal. Unfortunately the eastern section will always have tailwinds during the turns causing an overshoot of the flight lines. Simple solution is to have waypoint "40" come after "28". That results in only one downwind turn instead of 3 (or more depending on the size of the grid).

![image](https://user-images.githubusercontent.com/35429159/49346902-6106e280-f65e-11e8-84ad-d59150cf6669.png)


#2 - Add overshoot without adding a million extra waypoints. Missions are best kept simple. Straight-through waypoints do nothing and only clutter the mission. They're only useful if "breakup starts" is on.

![image](https://user-images.githubusercontent.com/35429159/49347018-a7107600-f65f-11e8-8e93-babfaf889d2f.png)


#3 - Break apart lead-in just like overshoot is broken up. Square corners can be turned well with the current navigation controllers. Acute ones often get ugly.

![image](https://user-images.githubusercontent.com/35429159/49347167-7e897b80-f661-11e8-8f42-ce86f2977722.png)

#4 - Fix the waypoint numbering in the survey (grid) window. Even without breakup starts, the waypoint numbers are incremented by two in the window. Once the waypoints are on the mission, they are incremented by 1.

![image](https://user-images.githubusercontent.com/35429159/49347253-3f0f5f00-f662-11e8-855b-6163b18849fd.png)

**Comment by meee1** [comment] 2018-12-03 10:42
1. this assumption assumes you are using plane. I do see your point however. (whats im really saying is there are different rules depending on the use case)
2. the extra points are needed depending on what mode you use (servo/digicam). The reason they are useful is it causes the navigation controller to pull tighter to the start of the survey area,, setting up the line the plane will have at the entry of the survey area. ie there is a more asserted effort to get online as the cross track error is higher, vs having a wp at the far end. it comes down to how the l1 controller is tuned.
3.  sounds doable.
4. the number on this screen has never been accurate. turn on internals and you will see.

**Comment by anestetico** [comment] 2018-12-06 22:46
This is the tomorrow survey and the difference between MP and Qgroundcontrol.
MP 1.3.61 build 1.3.6913.26037 (this is the best plan after tweaking the angle to 178
Qgroundcontrol 3.4.4 this is the first plan leaving 0 degrees angle
![capture](https://user-images.githubusercontent.com/6798659/49616317-2dde8f00-f98f-11e8-95b8-bd0e19f880a5.PNG)
![capture2](https://user-images.githubusercontent.com/6798659/49616318-2dde8f00-f98f-11e8-857a-8c7d65daf759.PNG)
![capture3](https://user-images.githubusercontent.com/6798659/49616319-2e772580-f98f-11e8-9044-01a510d55ee4.PNG)

**Comment by meee1** [comment] 2018-12-06 22:48
change your home location in MP as well to get similar results. looks like its set to bottom left at the moment.

**Comment by anestetico** [comment] 2018-12-06 22:53
![tlcapture](https://user-images.githubusercontent.com/6798659/49616727-8d896a00-f990-11e8-85cc-9b5ac7cc5104.PNG)
![trcapture](https://user-images.githubusercontent.com/6798659/49616728-8d896a00-f990-11e8-9cd9-5ea6d3552322.PNG)
![blcapture](https://user-images.githubusercontent.com/6798659/49616731-8e220080-f990-11e8-9c6b-b008fe10bc52.PNG)
![brcapture](https://user-images.githubusercontent.com/6798659/49616733-8e220080-f990-11e8-8d92-8ca35370e5f8.PNG)

**Comment by meee1** [comment] 2018-12-06 22:55
the only one you didn't try was home? which is what I suggested. just make sure its set correctly in flight planner first.

**Comment by meee1** [comment] 2018-12-06 22:56
also, you can drag the red marker around in the grid screen to tweak as well.

**Comment by anestetico** [comment] 2018-12-06 23:00
I tried home before but the home was inside the polygon, I put a fake home outside and it worked, I didn't knew it was like that, so how the "point" option works?
thank you very much, beautiful software
![homecapture](https://user-images.githubusercontent.com/6798659/49616953-4ea7e400-f991-11e8-9d4c-cd222df1db40.PNG)
![h2capture](https://user-images.githubusercontent.com/6798659/49616954-4f407a80-f991-11e8-8147-d04a83e7db39.PNG)

**Comment by Naterater** [comment] 2018-12-06 23:04
> 2\. the extra points are needed depending on what mode you use (servo/digicam). The reason they are useful is it causes the navigation controller to pull tighter to the start of the survey area,, setting up the line the plane will have at the entry of the survey area. ie there is a more asserted effort to get online as the cross track error is higher, vs having a wp at the far end. it comes down to how the l1 controller is tuned.

Sorry to go back to this topic, but the straight-through waypoints don't do any more to get on-line because the L1 controller controls the maximum approach angle. They don't bring it any tighter to the survey area. It's kind of a bug for ardupilot, but I'll have to do some flight testing or illustrations to show you what I mean.

Well done on the rest of the improvements. I agree, this survey grid manager is a beautiful piece of software that has excellent options and very clear definitions without any assumptions.

**Comment by meee1** [comment] 2018-12-09 01:04
@Naterater please show with tests. pretty sure im correct.
im closing this issue, as it address's the issue originally shown.

**Closed by meee1** 2018-12-09 01:04 UTC
