### ISSUE TITLE
Error when more than one parameter changed

### ISSUE THREAD

**Issue by night-ghost** [ArduPilot/MissionPlanner#1417] opened 2016-11-28 12:11 UTC
![mp](https://cloud.githubusercontent.com/assets/6255710/20667906/fd1783de-b595-11e6-9ad3-108455a44b27.png)

**Comment by meee1** [comment] 2016-11-28 12:25
can you tell me which parameters? ive been trying to track this down.

**Comment by night-ghost** [comment] 2016-11-28 12:29
any 2 or more parameters. 

fail here 
```

temp.Sort((a,b)=>
            {
                if (a == null || b == null) return 0;
                if (a.EndsWith("ENABLE")) return 1; return -1;
            });
```

**Comment by night-ghost** [comment] 2016-11-28 12:31
may be it will be better not to sort but instead make a parameters loop twice?

**Comment by meee1** [comment] 2016-11-28 12:32
the code has changed since the version you are using. I was trying to discover the cause while under the debugger. I'm pretty sure its fixed in the latest beta.

**Comment by night-ghost** [comment] 2016-11-28 12:33
this sort function not uses 'b' value at all so it REALLY is not consistent

**Comment by night-ghost** [comment] 2016-11-28 12:35
it should return 0 if both params with ENABLE or witout ENABLE

**Comment by night-ghost** [comment] 2016-11-28 12:38
just updated sources from Github - code is the same

```
temp.Sort((a,b)=>
            {
                if (a == null || b == null) return 0;
                if (a.EndsWith("ENABLE")) return 1; return -1;
            });
```

**Comment by meee1** [comment] 2016-11-28 12:39
i duno where your looking.

        static int sorter(string a, string b)
        {
            if (a == null || b == null) return 0;
            if (a.EndsWith("ENABLE") && b.EndsWith("ENABLE")) return a.CompareTo(b);
            if (a.EndsWith("ENABLE")) return -1;
            if (b.EndsWith("ENABLE")) return 1;
            return a.CompareTo(b);
        }

**Comment by night-ghost** [comment] 2016-11-28 12:44
Hmm sorry Git refuses to update. Looks much better and seems that should to work, but...

**Comment by night-ghost** [comment] 2016-11-28 13:46
just tested 1.3.41 - the same error :(

**Comment by meee1** [comment] 2016-11-28 13:46
you need MP beta
help > update beta.

**Comment by night-ghost** [comment] 2016-11-28 14:00
Ok thanks, Beta works fine! This error prevents me form [debugging this](https://www.rcgroups.com/forums/showthread.php?t=2784349) - EEPROM emulated in Flash so all parameters erased on each firmware upload and should be reloaded from file

**Comment by magicrub** [comment] 2016-11-28 17:09
wouldn't it be better to check for EndsWith("_ENABLE") with the _ in there?

**Comment by meee1** [comment] 2016-12-03 21:53
thanks for the report.

**Closed by meee1** 2016-12-03 21:53 UTC
