### ISSUE TITLE
Displaying geo-fence limits on map

### ISSUE THREAD

**Issue by Rupicapra-rupicapra** [ArduPilot/MissionPlanner#1165] opened 2016-03-04 11:16 UTC
Hello,
I would like to request a feature: adding an option to display the geo-fence limits around home location, based on the defined radius, on maps (in Flight Plan tab and Status tab). It would be helpful when creating a flight plan, to ensure that the defined waypoints are not out of that fence.
What do you think about this ?

Thanks a lot,
Rupi

**Comment by meee1** [comment] 2016-03-04 12:54
for plane or copter?

**Comment by Rupicapra-rupicapra** [comment] 2016-03-07 07:19
For copter.

**Comment by onurboy** [comment] 2016-04-10 19:53
Michael,
It's a good feature. Have you implemented it in latest beta?
Thanks.

Onur.

**Comment by rmackay9** [comment] 2021-06-28 23:40
This is a duplicate of https://github.com/ArduPilot/MissionPlanner/issues/456 so closing

**Closed by rmackay9** 2021-06-28 23:40 UTC
