### ISSUE TITLE
MissionPlanner 1.3.61 does no more show Modes in Log Browser

### ISSUE THREAD

**Issue by lorbass** [ArduPilot/MissionPlanner#2011] opened 2018-11-30 08:20 UTC
#### Issue details
The modifications in the Log Browser have destroyed the Mod Info.
Already in the last version the Graphs where instable.
Base Line shows sometimes 0 0 0 1 1 1 sometimes the line nr.
#### Version
1.3.61 

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Tailsitter

#### Hardware type
Pixhawk

#### Logs
https://drive.google.com/open?id=1WBTw4EdCpFqh4jdZDQ2qHQTw_2AeQihT

**Comment by meee1** [comment] 2018-11-30 09:42
duplicate of #2008

**Closed by meee1** 2018-11-30 09:42 UTC
