### ISSUE TITLE
Flight Plan's Spline view is straight for some tracks

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1454] opened 2017-01-12 02:30 UTC
In the current beta release I think something funny may have happened to the spline view.  If you look at the track from 2 to 3 in the image below, it appears straight for some reason.  Also the track from 4 to 5 is not straight but instead has a slight bend half way along it's length.
![splineview_noverysplineish](https://cloud.githubusercontent.com/assets/1498098/21874757/60243228-d8ba-11e6-8adb-fe58ed3f76de.png)

**Comment by meee1** [comment] 2017-01-12 09:46
i cant explain it, but something is wrong with the Grad %. I just tested here, and it looks ok
![image](https://cloud.githubusercontent.com/assets/511568/21884625/0b5b7924-d8ef-11e6-9434-d78c6f1866fc.png)

**Comment by meee1** [comment] 2017-01-12 09:52
somehow home alt is factoring in...

**Comment by meee1** [comment] 2017-01-12 09:54
the cause is because you have the altitude mode set to absolute. as relative it returns to normal. I will check what is going on
ie absolute home of 900 to absolute 25m

**Comment by meee1** [comment] 2017-01-12 09:58
after looking further, the result is correct.
the 3d velocity includes a very large z axis change, so the projected path is less noticeable on the x/y axis.

**Comment by magicrub** [comment] 2017-01-12 10:02
I've been bit by this in the past too. Since most people fly using
relative, would it be possible to post a warning msg once per boot if
waypoints are found in absolute mode?

**Comment by meee1** [comment] 2017-01-12 10:06
on upload MP check if the user meant absolute or not for this exact case

**Comment by meee1** [comment] 2017-01-12 10:13
@magicrub do you know how long ago it was you had issues
MP has checked since the end of 2015
https://github.com/ArduPilot/MissionPlanner/blame/master/GCSViews/FlightPlanner.cs#L2032

**Comment by meee1** [comment] 2017-01-12 10:21
make that start of 2013
https://github.com/ArduPilot/MissionPlanner/blob/8b2c5105c820e542d3fdc9668991763d78306a5d/GCSViews/FlightPlanner.cs#L1266

**Comment by magicrub** [comment] 2017-01-12 18:17
Eh? Was that tag for @rmackay9?

**Comment by meee1** [comment] 2017-01-21 04:08
closing, as is displaying correctly.

**Closed by meee1** 2017-01-21 04:08 UTC
